import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{ display: 'flex', gap: '2rem', padding: '1rem', background: '#e0f7e9', justifyContent: 'center' }}>
          <a href="/" style={{ textDecoration: 'none', color: '#217a4b', fontWeight: 'bold' }}>Home</a>
          <a href="/tips" style={{ textDecoration: 'none', color: '#217a4b', fontWeight: 'bold' }}>Tips</a>
          <a href="/pledge" style={{ textDecoration: 'none', color: '#217a4b', fontWeight: 'bold' }}>Pledge</a>
          <a href="/about" style={{ textDecoration: 'none', color: '#217a4b', fontWeight: 'bold' }}>About</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
